### ISSUE TITLE
Why adding identical asset

### ISSUE THREAD

**Issue by ameliacode** [PKU-MARL/DexterousHands#16]
Hi,
I have noticed that your mjcf robot is identical.
I don't understand why you loaded each assets. 
Does reusing asset has problem in isaac gym?

**Comment by cypypccpy** [comment]
Hi @ameliacode ,

Very meticulous observation. Yes, we use the identical asset, but isaacgym is fine to reuse the asset, so we can also just use one mjcf file in bi-dexhands. 

As for why we use another identical mjcf in bi-dexhands, it is because we want to distinguish different robots by name. 

For example, in [https://github.com/PKU-MARL/DexterousHands/blob/main/bi-dexhands/tasks/shadow_hand_over.py](https://github.com/PKU-MARL/DexterousHands/blob/main/bi-dexhands/tasks/shadow_hand_over.py):

![image](https://user-images.githubusercontent.com/55881363/209132543-b9374345-3113-4741-92a6-8ad01f7ca8d3.png)

The official ShadowHand mjcf define the hand as robot0:

![image](https://user-images.githubusercontent.com/55881363/209132828-461ce8c7-1587-476b-8a70-55f09221ca21.png)

so we rewrote a copy of the same mjcf ourselves, the difference is that the prefix is changed to robot1, so we can better distinguish them in the code.

Hope this can help you.
