### ISSUE TITLE
Issues with rl_games

### ISSUE THREAD

**Issue by jiangranlv** [PKU-MARL/DexterousHands#19]
Hi, @cypypccpy nice work!
when I try to run train_rlgames.py, I met the error
![图片](https://user-images.githubusercontent.com/66426987/222077334-0abca10f-6f9e-4ffd-b01c-ccaca8cb242f.png)
It seems like incompatible between rlgames and isaacgym, however I don't find any similar situation like mine.
Furthermore, I found the key variant is  'env' which is a 'RLgamesVecTaskPython' class that can't be loaded into 'rl-games Runner'
![图片](https://user-images.githubusercontent.com/66426987/222079056-deaf1d81-e577-416c-b311-76e0d5791817.png)

please help me, thx!!!

**Comment by cypypccpy** [comment]
Hi @jiangranlv ,

Thanks! The reason for this error is due to the version with rlgames. Currently, Bi-DexHands has only been tested to support version 1.5.2 of rlgames (the version I used when developing this feature). Therefore, you can simply solve this problem by uninstalling rlgames and installing version 1.5.2:
```
pip uninstall rl-games
pip install rl-games==1.5.2
```
I do plan to support the new version of rlgames, but I may not have time at this moment QAQ. Fortunately, I think version 1.5.2 of rlgames can still be used very well. I will update this message in the README. If you still can't use it after changing the version, please contact me in this issue. And if you are interested, we also welcome you to submit a PR to help us with this issue.

Hope this can help you.

**Comment by jiangranlv** [comment]
> Hi @jiangranlv ,
> 
> Thanks! I'm sorry for this issue. The reason for this error is due to the version with rlgames. Currently, Bi-DexHands has only been tested to support version 1.5.2 of rlgames (the version I used when developing this feature). Therefore, you can simply solve this problem by uninstalling rlgames and installing version 1.5.2:
> 
> ```
> pip uninstall rl-games
> pip install rl-games==1.5.2
> ```
> 
> I do plan to support the new version of rlgames, but I may not have time at this moment QAQ. Fortunately, I think version 1.5.2 of rlgames can still be used very well. I will update this message in the README. If you still can't use it after changing the version, please contact me in this issue. And if you are interested, we also welcome you to submit a PR to help us with this issue.
> 
> Hope this can help you.

**Comment by jiangranlv** [comment]
Thank you very much!!!!
